[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv
board_build.flash_size = 4MB
upload_speed = 115200
build_flags =
    -I managed_components/espressif__led_strip/include
    -I managed_components/joltwallet__littlefs/include